import { ReactNode } from "react";
import Head from "next/head";
import MainHeader from "./Header";
import Footer from "./Footer";
import {
    Box,
}from "@chakra-ui/react";

interface IProps {
    children: ReactNode;
}


const MainLayout = ({children}: IProps) =>{
    return(
        <>
        <Head>
            <title>EventFlow</title>
            <meta name="description" content="Generated by create next app" />
        </Head>
        <Box
         w="100%"
         minH="100vh"
        >
            <MainHeader />
            {children}
        </Box>
        
        </>
    )
}


export default MainLayout